env:
  browser: true
  es6: true
  node: true
  mocha: true
plugins:
  - react
parserOptions:
  ecmaFeatures:
    jsx: true
  sourceType: module
extends: 'eslint:recommended'
rules:
  no-trailing-spaces: error
  comma-spacing:
    - error
    - {
      before: false,
      after: true
    }
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  jsx-quotes:
    - error
  semi:
    - error
    - always
  react/jsx-uses-vars: 1
globals:
  #library
  $: true
  _: true
  sinon: true
  assert: true

  #MF
  microModule: true
  MicroModule: true
  App: true